<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Sun Dec 25 2022 17:17:33 GMT+0100 (Mitteleuropäische Normalzeit)). */
return array(
	'mobx' => '4.15.4',
	'react' => '16.13.1',
	'react-dom' => '16.13.1'
);
